import turtle
turtle.title("Dibujando Logos")

def main():
    window = turtle.Screen()
    Miguel = turtle.Turtle()

    opcion = input("que deseas dibujar ? : Logo Plazi presione (A): Logo Python presione (B): ")

    if opcion.upper() == "A":
        logo_platzi(Miguel)
        turtle.mainloop()

    if opcion.upper() == "B":
        logo_python(Miguel)
        turtle.mainloop()

    else :
        print("No Eligio una figura")


def logo_platzi(Miguel):
    Miguel.pencolor("green")
    Miguel.fillcolor("green")
    Miguel.pensize(5)

    Miguel.begin_fill()
    Miguel.left(45)
    Miguel.forward(137.5)
    Miguel.left(45)
    Miguel.forward(12.5)
    Miguel.left(45)
    Miguel.forward(187.5)
    Miguel.left(45)
    Miguel.forward(12.5)
    Miguel.left(45)
    Miguel.forward(237.5)
    Miguel.left(45)
    Miguel.forward(12.5)
    Miguel.left(45)
    Miguel.forward(237.5)
    Miguel.left(45)
    Miguel.forward(12.5)
    Miguel.left(45)
    Miguel.forward(100)
    Miguel.left(90)
    Miguel.forward(50)
    Miguel.left(90)
    Miguel.forward(50)
    Miguel.left(270)
    Miguel.forward(150)
    Miguel.left(270)
    Miguel.forward(150)
    Miguel.left(270)
    Miguel.forward(100)
    Miguel.left(270)
    Miguel.forward(100)
    Miguel.left(90)
    Miguel.forward(50)
    Miguel.end_fill()
    Miguel.hideturtle()
    turtle.mainloop()

def logo_python(Miguel):
    Miguel.pencolor("navyblue")
    Miguel.fillcolor("navyblue")
    Miguel.pensize(5)

    Miguel.begin_fill()
    Miguel.left(0)
    Miguel.forward(100)
    Miguel.left(45)
    Miguel.forward(50)
    Miguel.left(45)
    Miguel.forward(100)
    Miguel.left(45)
    Miguel.forward(50)
    Miguel.left(45)
    Miguel.forward(100)
    Miguel.left(45)
    Miguel.forward(50)
    Miguel.left(45)
    Miguel.forward(40)
    Miguel.left(90)
    Miguel.forward(100)
    Miguel.left(270)
    Miguel.forward(15)
    Miguel.left(270)
    Miguel.forward(150)
    Miguel.left(45)
    Miguel.forward(50)
    Miguel.left(45)
    Miguel.forward(100)
    Miguel.left(45)
    Miguel.forward(50)
    Miguel.left(45)
    Miguel.forward(40)
    Miguel.left(90)
    Miguel.forward(45)
    Miguel.left(315)
    Miguel.forward(65)
    Miguel.end_fill()

    Miguel.penup()#subir el lapiz
    Miguel.left(45)
    Miguel.forward(140)
    Miguel.left(90)
    Miguel.forward(-12)
    Miguel.pendown()#Bajar el lapiz

    Miguel.fillcolor("white")#DIBUJO OJO #1
    Miguel.begin_fill()
    Miguel.pencolor("white")
    Miguel.left(90)
    Miguel.forward(20)
    Miguel.left(90)
    Miguel.forward(20)
    Miguel.left(90)
    Miguel.forward(20)
    Miguel.left(90)
    Miguel.forward(20)
    Miguel.end_fill()


    Miguel.penup()#subir el lápiz
    Miguel.left(90)
    Miguel.forward(160)
    Miguel.left(90)
    Miguel.forward(100)
    Miguel.pendown()#Bajar el lápiz
    
    Miguel.fillcolor("orange")
    Miguel.pencolor("orange")
    Miguel.begin_fill()
    Miguel.left(180)
    Miguel.forward(100)
    Miguel.left(45)
    Miguel.forward(50)
    Miguel.left(45)
    Miguel.forward(100)
    Miguel.left(45)
    Miguel.forward(50)
    Miguel.left(45)
    Miguel.forward(100)
    Miguel.left(45)
    Miguel.forward(50)
    Miguel.left(45)
    Miguel.forward(40)
    Miguel.left(90)
    Miguel.forward(100)
    Miguel.left(270)
    Miguel.forward(15)
    Miguel.left(270)
    Miguel.forward(150)
    Miguel.left(45)
    Miguel.forward(50)
    Miguel.left(45)
    Miguel.forward(100)
    Miguel.left(45)
    Miguel.forward(50)
    Miguel.left(45)
    Miguel.forward(40)
    Miguel.left(90)
    Miguel.forward(45)
    Miguel.left(315)
    Miguel.forward(65)
    Miguel.end_fill()

    Miguel.penup()#subir el lápiz
    Miguel.left(45)
    Miguel.forward(140)
    Miguel.left(90)
    Miguel.forward(-12)
    Miguel.pendown()#Bajar el lápiz

    Miguel.fillcolor("white") #Dibujando OJO #2
    Miguel.begin_fill()
    Miguel.pencolor("white")
    Miguel.left(90)
    Miguel.forward(20)
    Miguel.left(90)
    Miguel.forward(20)
    Miguel.left(90)
    Miguel.forward(20)
    Miguel.left(90)
    Miguel.forward(20)
    Miguel.end_fill()
    Miguel.hideturtle()

if __name__ == "__main__":
    main()